#
# Copyright 2017 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-deltalake-streaming
  namespace: sp1
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "gcr.io/mapr-252711/apache-spark-py-3.1.1:202107111721"
  imagePullPolicy: Always
  imagePullSecrets:
    - imagepull
  mainApplicationFile: "s3a://vivek/streaming.py"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    # Note: If you run app in tenant namespace - change serviceAccount name to "hpe-<namespace>"
    serviceAccount: hpe-sp1
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 3.1.1
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  sparkConf:
    "spark.hadoop.fs.s3a.endpoint": "http://10.1.100.74:10038"  # minio endpoint
    "spark.hadoop.fs.s3a.access.key": "admin" # minio access key
    "spark.hadoop.fs.s3a.secret.key": "admin123" # minio secret key
    "spark.hadoop.fs.s3a.impl": org.apache.hadoop.fs.s3a.S3AFileSystem
  deps:
    pyFiles:
      - s3a://vivek/delta.zip
    jars:
      - local:///opt/spark/deltalake/jars/delta-core_2.12-1.0.0.jar
      - local:///opt/spark/deltalake/jars/hadoop-aws-3.2.0.jar
      - local:///opt/spark/deltalake/jars/aws-java-sdk-bundle-1.11.1026.jar
